name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
    - name: coverlet
      uses: b3b00/coverlet-action@1.0.91
      with:
        testProject: 'Regulus.RelationalTables.Tests/Regulus.RelationalTables.Tests.csproj'
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.1
      with:         
        github-token: ${{ secrets.CODECOV_TOKEN }}
        path-to-lcov: ${{steps.coverlet.outputs.coverageFile}} 

